### ISSUE TITLE
DIO input ouput crash

### ISSUE THREAD

**Issue by jcul3351** [strykeforce/thirdcoast#13]
If you watch the DIOs as inputs, things work fine all the way through the grahper.  But if you then use TCT to control a selected DIO as an output, TCT crashes
![selecting digital output error](https://user-images.githubusercontent.com/26776204/32984389-b294574c-cc73-11e7-8f1d-399a082a42fb.JPG)

**Comment by jhh** [comment]
The way this is going to work, is once you assign something as an output it is removed from the inputs for the rest of the current `tct` session.

**Comment by jcul3351** [comment]
Any way to watch what is output on the grapher?  Or do you just need to remember what you commanded in TCT?

**Comment by jhh** [comment]
The grapher has a digital output item for everything you've previously selected as an output and will allow you to display setpoint.

**Comment by jcul3351** [comment]
excellent

Jerry
