### ISSUE TITLE
TCT launch

### ISSUE THREAD

**Issue by jcul3351** [strykeforce/thirdcoast#14]
This is minor ...

When you launch TCT, there is a small delay before you see anything happen.  Is there a way to do some dot across the screen or some type of activity so that the moment you hit enter, you know something is going on.  Just thinking about user comfort.

**Comment by jhh** [comment]
We print out the name and version first thing, so any delay between launch and seeing that is due to the JVM startup and WPI library code. Try putting something like this in the `tct` startup script:

```
#!/bin/sh
echo tct starting... # add this line
/usr/local/frc/JRE/bin/java -Djava.library.path=/usr/local/frc/lib/ -jar tct.jar
```

**Comment by jcul3351** [comment]
I am guessing the instructions below got a little garbled.

Here is what I did:

#!/bin/sh/usr/local/frc/JRE/bin/java -Djava.library.path=/usr/local/frc/lib/ -jar /home/admin/tct.jar 2> /dev/null
#!/bin/sh/usr/local/frc/JRE/bin/java -Djava.library.path=/usr/local/frc/lib/ -jar tct.jar

Is that what you intended?

It did not seem to make any difference.  The delay is not really a big deal.  I just figured if there was a way to address it, we might as well.

**Comment by jhh** [comment]
Sorry if garbled, to make it easier I put a gist here: https://gist.github.com/jhh/d43154a753404b868362cd41bd425407

You can download it or just copy and paste it into the `tct` start script. All it does is print out a `tct starting, please wait...` before anything else happens since we can't do anything about the WPI initialization duration. I think it helps though, because it doesn't look like it is hanging.

You will see this at startup:

```sh
admin@roboRIO-2767-FRC:~# ./tct
tct starting, please wait...
********** Robot program starting **********
Third Coast Telemetry Utility (tct) 17.1.0

 1 - Work with Talons
 2 - Work with Servos
 3 - Work with Digital Inputs and Outputs
 4 - Quit
select> 4                                                             [disabled]
Bye.
```

**Comment by jcul3351** [comment]
That worked and you do get the message right away.  But you also get an error.

**Comment by jhh** [comment]
Hmm.. I just cut and pasted the gist again and it works. Can you post the error you're seeing?

**Comment by jcul3351** [comment]
I attached it to the last post.  Did it not come through?

Jerry
