### ISSUE TITLE
Add Motion Magic Grapher Values

### ISSUE THREAD

**Issue by jhh** [strykeforce/thirdcoast#21]
```java
getMotionMagicAcceleration()
getMotionMagicActTrajPosition()
getMotionMagicActTrajVelocity()
getMotionMagicCruiseVelocity()
```

**Comment by sidpagariya** [comment]
So where can we add these functions?

**Comment by jhh** [comment]
1. New `Measure` enums are defined [here](https://github.com/strykeforce/thirdcoast/blob/master/core/src/main/java/org/strykeforce/thirdcoast/telemetry/grapher/Measure.java)
2. Enums are added [here](https://github.com/strykeforce/thirdcoast/blob/6dc68ae384fd6825494838e8009be8a7788fcf58/core/src/main/java/org/strykeforce/thirdcoast/telemetry/item/TalonItem.java#L19)
3. Code to take measurements (see functions in orig. post) are added to this [switch statement](https://github.com/strykeforce/thirdcoast/blob/6dc68ae384fd6825494838e8009be8a7788fcf58/core/src/main/java/org/strykeforce/thirdcoast/telemetry/item/TalonItem.java#L67). Note they are added as method references if possible.

**Comment by sidpagariya** [comment]
Okay, that's what I thought for `Measure` enums... but I didn't know what the `TalonItem` measures were for...
We basically need to add those three in the three places, correct?
