### ISSUE TITLE
V17.0.22 problems

### ISSUE THREAD

**Issue by jcul3351** [strykeforce/thirdcoast#8]
Something got missed here.
1. While the analog raw shows up in TCT, it does not show up in the Grapher.  And I did see it work at midlink with my own eyes.  
2. The order of the frame rate settings is not changed.  General is not first.
3. The servos and the DIO output stuff does work.
4. I downloaded and confirmed V22 made it all the way to the Roborio twice.

**Comment by jhh** [comment]
I neglected to merge these changes in develop into the master branch, should be fixed in the next version going up.

**Comment by jcul3351** [comment]
Thanks

Jerry
