### ISSUE TITLE
A question about motion magic in your swerve control

### ISSUE THREAD

**Issue by mendax1234** [strykeforce/thirdcoast#91]
l notice that this lib uses motion magic to control the turning motor. However , how do you calculate your paarameters like kP,kD , motioncurisevelocity , motionacceleration and so on? Would you provide any advice. l have read the CTRE's docs about motion magic, but l still don't know how to tune these parameters?

Any answer is appreciated!

**Comment by jhh** [comment]
Our mentor who has 30+ years of electric motor control system development made a video tutorial series on YouTube that walks through the process. You'll see some motion magic specific stuff in chapter 8, but the earlier chapters are very useful if you're new to PID loop tuning.

You can find a description and links on our web sites [resources page](https://www.strykeforce.org/resources/), specifically the **Stryke Force Talon SRX Motor Training Course** section.

**Comment by mendax1234** [comment]
`Our mentor who has 30+ years of electric motor control system development made a video tutorial series on YouTube that walks through the process. You'll see some motion magic specific stuff in chapter 8, but the earlier chapters are very useful if you're new to PID loop tuning.`

Thanks for providing such an useful video. l have dug into it before and l just have some questions about your motion magic in chapter 8 . At first, your mentor says that we should start from kF. 
- So, at this time , should l set all other parameters such as kP,kD,kI and so on to 0 and tune the kF only , and the talon srx can reach the desired speed closely?
- Besides, after l have tuned the kf of my talonSRX , l notice that your excel will calculate a set of kP ,kD , kCruiseVelocity and kCruiseAcceleration , how does it do that? If l don't have your tuning tool--Grapher, l just have phoneix tuner, how to tune these parameters(kP,kD,kCruiseVelocity and kCruiseAcceleration)? Which one should l start tuning from ? Is there any specefic steps to do it? In the Chapter video , it seems that your mentor didn't say how to do it.

Any answer is appreciated!

**Comment by jhh** [comment]
I'm closing this as it was answered on Chief Delphi.
